dist: bionic

language: python
python:
    - "3.7"

before_install:
    - sudo pip install pipenv

install:
    - pipenv --three sync
    - pipenv install travis-sphinx

script:
    - pipenv run python -c "import mathematics"
    - pipenv run travis-sphinx build -s source

after_success:
    - pipenv run travis-sphinx deploy
