language: python - "3.7"

# before_install will simply setup a conda enviroment for installing python packages, if you
# have project dependencies it's usually recommended to go this route
before_install:
    - pip install --user pipenv

install:
    - pipenv --three install
    - pipenv install travis-sphinx

script:
    - pipenv run travis-sphinx build -s source

after_success:
    - pipenv run travis-sphinx deploy
